blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_details'),
]

portafolio_django/urls.py
from django.conf import settings
from django.conf.urls.static import static

"""
URL configuration for portafolio_django project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('about/', views.about, name='about'),
    path('projects/', views.projects, name='projects'),
    path('contact/', views.contact, name='contact'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images',
                              height_field=None, width_field=None, max_length=None)
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models


OPCIONES = [
    (0, '0'),
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, '7'),
    (8, '8'),
    (9, '9'),
    (10, '10'),
]

# Create your models here.

# modelo creado para la seccion de proyectos


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    url_github = models.URLField(blank=True)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self) -> str:
        return self.title


class Skill(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='portafolio/icon-skill')
    experiencia = models.IntegerField(choices=OPCIONES, default=0)

    def __str__(self) -> str:
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
# Create your views here.

# vista que dirije a pagina principal de los post


def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})


# esta vista dirije a la pagina detellada de cada post
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id) #si no encuentra el objecto devuelve pagina 404
    return render(request, 'post_details.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project, Skill
# Create your views here.


def home(request):
    projects = Project.objects.all()
    skills = Skill.objects.all()

    return render(request, 'home.html', {'projects': projects, 'skills': skills})


def about(request):
    return render(request, 'about.html')


def projects(request):
    return render(request, 'projects.html')


def contact(request):
    return render(request, 'contact.html')

blog/templates/post_details.html
{% extends 'layout.html' %} {% block content %}
<h1>post details</h1>

<h2>{{post.title}}</h2>
<h4>{{post.date}}</h4>
<p>{{post.description}}</p>
<img src="{{post.image.url}}" alt="{{post.image.url}}" />
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %} {% block content %}
<h1>post</h1>

{% for post in posts %}
<h2>{{post.title}}</h2>
<h4>{{post.date|date:'d M Y'}}</h4>
<p>{{post.description|truncatechars:100}}</p>
<img src="{{post.image.url}}" alt="{{post.image.url}}" />
<a href="{% url 'blog:post_details' post.id %}">{{post.title}}</a>
{% endfor %} {% endblock %}

portfolio/templates/about.html
{% extends "layout.html" %} {% block content %}

<h2>section about</h2>
{% endblock %}

portfolio/templates/components/navbar.html
{% load static %}
<!--navbar-->
{% comment %}
<nav class="navbar">
  <div class="container-navbar">
    <div class="logo">
      <a href="#home"
        ><img src="{% static 'img/django-img.jpg' %}" alt="Logo"
      /></a>
    </div>
    <div class="menu">
      <ul>
        <li><a href="{% url 'home' %}">Inicio</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url 'projects' %}">Projects</a></li>
        <li><a href="{% url 'contact' %}">Contacto</a></li>
      </ul>
    </div>
    <button class="button-small" href="{% url 'blog:posts' %}">Blog</button>
  </div>
  {% endcomment %}

  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img
          src="{% static 'img/python.png' %}"
          alt="logo"
          style="height: 40px" />
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Skills</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
        <div class="d-flex" role="search">
          <button
            href="{% url 'blog:posts' %}"
            class="btn button-small"
            type="submit">
            BLOG
          </button>
        </div>
      </div>
    </div>
  </nav>
</nav>

portfolio/templates/contact.html
{% extends "layout.html" %} {% block content %}
<h2>seccion de contacto</h2>
{% endblock %}

portfolio/templates/home.html
{% extends "layout.html" %} {% load static %} {% block content %}

<!--header-->

<header>
  <div class="header-class">
    <h2 class="nombre-header">SoySebastian</h2>
    <h1>Full Stack developer</h1>
    <h1>Python</h1>
    <button class="button-large button-header">Ver Proyectos</button>
  </div>
</header>

<main>
  <!--seccion about-->
  <section id="about">
    <div class="container-about">
      {% comment %} <div class="img-about">
        <img src="{% static 'img/setup-dog.jpg' %}" alt="Sobre mí" />
      </div> {% endcomment %}
      <div class="description-about">
        <h3>Sobre mí</h3>
        <p>
          ¡Hola! Soy Sebastián, un Desarrollador Full Stack con experiencia en Python. 
          Me apasiona crear aplicaciones web eficientes y escalables. Siempre estoy aprendiendo y mejorando mis habilidades en frontend y backend.
        </p>
        <p>
          Fuera del trabajo, disfruto explorando nuevas tecnologías y contribuyendo a 
          proyectos de código abierto. ¡Conectemos y hablemos de tecnología!
        </p>
      </div>
    </div>
  </section>

  <!--seccion tecnologias-->
  <section id="skills">
    <div class="section-skills">
      <h2 class="title-section">TECNOLOGIAS</h2>
      <div class="container-skills">
        {% for skill in skills %}
        <div class="card-skills">
          <img src="{{skill.image.url}}" alt="{{skill.title}}" />
          {{skill.title}}
        </div>
        {% endfor %}
      </div>
    </div>
  </section>



  <!--seccion proyectos 2-->
  <section id="projects">
    <h2 class="title-section">MIS PROJYECTOS</h2>
    <div class="container-project row">
      {% for project in projects %}
      <div class="col-md-6 container-card">
        <div class="card mx-auto" style="width: 32rem">
          <img
            src="{{project.image.url}}"
            class="img-fluid img-card-project"
            alt="{{project.title}}" />
          <div class="card-body">
            <h5 class="card-title">{{project.title}}</h5>
            <p class="card-text">{{project.description}}</p>
          </div>
          <ul class="list-group list-group-flush tag-container">
            <li class="list-group-item">
              {% for tag in project.tags.all %}
              <span class="tag-element">#{{ tag }}</span>
              {% endfor %}
            </li>
          </ul>
          <div class="card-body button-container">
            {% if project.url_github %}
            <a href="{{project.url_github}}" class="card-link button-card">
              <i class="fa-brands fa-github"></i> Codigo del Proyecto
            </a>
            {% endif %} {% if project.url %}
            <a href="{{project.url}}" class="card-link button-card">
              <i class="fa-solid fa-arrow-up-right-from-square"></i> Url del
              proyecto
            </a>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>

  <!--seccion contacto-->
  <section id="contact">
    <h2 class="title-section">Contacto</h2>
    <div class="container-contact">
      <div class="container-info">
        <div class="container-text">
          <h3>Informacion de contacto</h3>
          <p>
            On the other hand, we denounce with righteous indignation and
            dislike
          </p>
        </div>
        <div class="container-icon">
          <div class="icon-contact">
            <div class="icons">
              <div class="items-icon">
                <a href="{{project.github_url}}" class="card-link">
                  <span>
                    <i class="fa-brands fa-github fa-2x"></i>
                  </span>
                  Git Hub
                </a>
              </div>
              <div class="items-icon">
                <a href="{{project.behance_url}}" class="card-link">
                  <span>
                    <i class="fa-brands fa-behance fa-2x"></i>
                  </span>
                  Behance
                </a>
              </div>
              <div class="items-icon">
                <a href="{{project.linkedin_url}}" class="card-link">
                  <span>
                    <i class="fa-brands fa-linkedin fa-2x"></i>
                  </span>
                  Linkedin
                </a>
              </div>
            </div>
            <div class="email">
              <div class="item-mail">
                <h6>Mi mail directo</h6>
                <p>msebastiandelajara@gmail.com</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="container-form">
        <form action="/enviar" method="POST">
          <div class="div-input">
            <input
              class="item-form"
              type="text"
              id="nombre"
              name="nombre"
              placeholder="Nombre"
              required /><br />
          </div>

          <div class="div-input">
            <input
              class="item-form"
              type="email"
              id="email"
              name="email"
              placeholder="Email"
              required /><br />
          </div>

          <div class="div-input">
            <textarea
              class="item-form"
              id="mensaje"
              name="mensaje"
              rows="4"
              placeholder="Comentario"
              required></textarea
            ><br />
          </div>

          <input class="item-form" type="submit" value="Enviar" />
        </form>
      </div>
    </div>
  </section>
</main>

{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mi portafolio</title>
    <!--5.3.3/dist/js/bootstrap.bundle.min.js-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!--google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Prompt:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet" />
      <script
        src="https://kit.fontawesome.com/aa15fc2397.js"
        crossorigin="anonymous"></script>
    <!--css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  </head>
  <body>
    {% include 'components/navbar.html' %} {% block content %} {% endblock %}

    <footer>
     
      <div class="container-footer">
        <hr>
        <div class='inner-footer'>
          <p class='parraf-footer'>Construido con <strong>Django</strong>.</p>
        </div>
        <p class='bottom-footer'>Sebastian De La Jara © 2021</p>
      </div>
    </footer>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static "js/script.js" %}"></script>
  </body>
</html>

portfolio/templates/projects.html
{% extends "layout.html" %} {% block content %}

<h2>pagina de proyectos</h2>

{% endblock %}